### ISSUE TITLE
Get all the projects set up with GitHub projects, basic wikis, issue tracking and milestones

### ISSUE THREAD

**Issue by mattl** [creativecommons/meta#1]
Hey Sarah,

Thanks for getting the wiki page up with the projects. The next step is to assign people to all of the project drivers, and make GitHub projects for each of them.

Each one will need:

* a template on the wiki explaining who are the Driver, Approvers, Contributors and Involved people for the project.
* a GitHub team for the project with the same people added.
* some starter milestones added to their issue tracker (see how I've added them here for reference, maybe that's a good way to go, maybe not?)
* labels for the various aspects of the project --- these will vary from project to project, but we can talk to the driver to get these going
* an initial issue from the driver that talks about the overall scope of the project, what the project aims to fix, etc.

Luckily, between you and I we have all the skills and information needed to make these things happen!

What do you think? What are our next steps?

**Comment by sarahpearson** [comment]
Before we create the GitHub projects for each one, I think we should have everyone glance at the list to make sure it is accurate and complete. (For example, I'm talking to Diane in about two hours about who will be driver of each of ours.) 

We also need people to take action if they have a project that was flagged as needing reconsideration against our strategic priorities. I think we can go ahead and make GitHub projects for those, but perhaps the first issue filed under each of those is to make that reassessment with the relevant people.. 

I'll email staff asking them all to take a look at the list today so we can move ahead. Sound like a plan?

**Comment by mattl** [comment]
Better... let me finish getting everyone's GitHub username, and I'll make an issue for each person to check their projects. Ryan has a couple that are flagged and he won't be back until next week.

**Comment by sarahpearson** [comment]
Perfect.

**Comment by janeatcc** [comment]
re "We also need people to take action if they have a project that was
flagged as needing reconsideration against our strategic priorities. I
think we can go ahead and make GitHub projects for those, but perhaps the
first issue filed under each of those is to make that reassessment with the
relevant people.."

I forget all the ones I'm on point for that were flagged. I imagine someone
took pictures and you guys have it somewhere on record?

On Mon, Feb 23, 2015 at 10:52 AM, Sarah Pearson <notifications@github.com>
wrote:

> Perfect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/meta/issues/1#issuecomment-75606234>.
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by sarahpearson** [comment]
Yes, they are noted in this list: 

https://github.com/creativecommons/meta/wiki

**Comment by mattl** [comment]
@janeatcc i flagged them with a bold text for now. i saw you put a question mark next to them, but they're all consitently (re)marked with **[this one was flagged for reconsideration with priorities]** for now.

**Comment by sarahpearson** [comment]
There are also a few (open education awareness, open policy, individual artists outreach) that feel less like concrete projects and more like our day-to-day work. Do those need separate github repositories? For the most part, it feels like we left off that type of work. Could be that I just don't know what those three encompass, just raising the issue to make sure we're consistent.

**Comment by janeatcc** [comment]
Agree, I would get rid of "individual artists outreach" for me.

I'm still not clear on what "Encourage new adoptions" is or where it came from?

I think it's worth keeping "Cultural institutions/GLAM adoptions and outreach" as we need to figure out whether we still want to do this?

Lastly, are people ok with me re-categorizing the projects under our strategic goals? I thought we agreed to get away from program silos... the current categories sort of keep those..

**Comment by mattl** [comment]
Yes to moving things under the various goals. Ping us if we can help.

**Comment by janeatcc** [comment]
Ok - reorganized. I'm thinking of also deleting "encouraging new adoptions"
as I have no idea what it is but it sounds like something we do on an
ongoing basis anyway.

On Mon, Feb 23, 2015 at 3:05 PM, Matt Lee <notifications@github.com> wrote:

> Yes to moving things under the various goals. Ping us if we can help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/meta/issues/1#issuecomment-75657679>.
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by peterspdx** [comment]
There are a few entries I didn't understand, because they seem very general and what we do every day without specific metrics. Those are Encouraging new adoptions, Open education awareness, and Open policy.  Would like to see those made concrete if we keep them as they seem very open ended.  My other concern is the "flagged for reconsideration".  That seems to mean different things depending on the item marked.  Watching the ITW session, the meaning of thumbs'  up changed midstream, from "don't pursue" to "let's decide whether or not to pursue it after further analysis".  I thought the consensus was the latter for all but one or two of them.  Finally, note that two are added:  Collecting society engagement (this is ensuring NC licenses are accounted for in Europe per collecting society directive implementations) and the Best practices for attribution project that Ryan OK'd a bit ago to be led by Paul Stacey based on a project he and Sarah are working on for BCCampus.

**Comment by sarahpearson** [comment]
@janeatcc I think the adoption one was a subset of platforms. Please go ahead and delete if you don't think it warrants a separate project. Also, sounds good to have GLAM on there if we are making a go or no-go decision about resources. 

@peterspdx I was thinking more about the "flagged for reconsideration" and I definitely agree there was confusion. I do think there is a difference between going forward to do an analysis and thinking about whether even the analysis itself is the best use of time. That might account for some of the sideways thumbs, at least from me personally. I think for each of the flagged projects, the first to-do is to get to the bottom of the reconsideration, whether that means a call with individual people, staff discussion, etc. 

As for the vague ones, if Jane deletes "new adoptions," that leaves open policy and open education awareness. @tvol, do you think open policy should have a separate github project? (I don't see Cable's name popping up here yet so may need to email him about the OER one..)

**Comment by janeatcc** [comment]
I deleted the "encourage new website adoptions."

On Tue, Feb 24, 2015 at 4:58 AM, Sarah Pearson <notifications@github.com>
wrote:

> @janeatcc <https://github.com/janeatcc> I think the adoption one was a
> subset of platforms. Please go ahead and delete if you don't think it
> warrants a separate project. Also, sounds good to have GLAM on there if we
> are making a go or no-go decision about resources.
>
> @peterspdx <https://github.com/peterspdx> I was thinking more about the
> "flagged for reconsideration" and I definitely agree there was confusion. I
> do think there is a difference between going forward to do an analysis and
> thinking about whether even the analysis itself is the best use of time.
> That might account for some of the sideways thumbs, at least from me
> personally. I think for each of the flagged projects, the first to-do is to
> get to the bottom of the reconsideration, whether that means a call with
> individual people, staff discussion, etc.
>
> As for the vague ones, if Jane deletes "new adoptions," that leaves open
> policy and open education awareness. @tvol <https://github.com/tvol>, do
> you think open policy should have a separate github project? (I don't see
> Cable's name popping up here yet so may need to email him about the OER
> one..)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/meta/issues/1#issuecomment-75751690>.
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by tvol** [comment]
@sarahpearson I agree with your earlier note and think the "open policy" should be deleted. I vaguely recall that when we were putting those stickies up we consciously avoided placing things there that were "core" (more or less). And open policy outreach is just something we do day to day. One thing that I did add that wasn't there before is foundation policy engagement (since we're actively doing that via the Fund for Shared Insight grant).

**Comment by mattl** [comment]
@tvol go ahead and remove any that you think don't belong up there. Also, can you make sure the drivers are correct for any things you have with Cable?

**Comment by sarahpearson** [comment]
@mattl Do you think we should get github projects set up for everything on the list before the staff meeting tuesday, or wait until after that so we can discuss ambiguous ones/etc? I'm neutral.

**Comment by mattl** [comment]
for all the ones that aren't uncertain, yes.

**Comment by sarahpearson** [comment]
ok. Github says I have insufficient permissions to set them up?

**Comment by mattl** [comment]
erk. sorry.. try now.

**Comment by mattl** [comment]
https://github.com/creativecommons/meta/wiki/Adding-CC-projects-to-GitHub

**Comment by sarahpearson** [comment]
I've added all projects on the list except (1) projects where @mattl is the driver because he can add those; and (2) projects flagged with a sideways thumb. We can add those after we discuss at the staff meeting on tuesday.

**Comment by janeatcc** [comment]
Is there a reason why only some projects are listed in the table from the bullets? eg. SOO. or is it just an oversight

Also, I think we should add another project "Strategic engagement with start-ups"  - while this includes start-up platforms it is larger than that so should be its own thing. But this probably requires discussion. So let me know if I should add it or wait until tomorrow

**Comment by mattl** [comment]
I just made one table to show Sarah how we can make tables in the wiki. I
think the table method looks a lot nicer.

**Comment by sarahpearson** [comment]
Finished making the table for the project list. (@mattl, I didn't create projects for yours. let me know if you want me to)

@janeatcc let's wait to create one for the startup engagement until after the meeting today, so we know who the driver is, etc.

**Comment by sarahpearson** [comment]
p.s. I would love to be the initial driver on the startup work! ties in nicely with the open business models work and a presentation I am giving in May..

**Comment by sarahpearson** [comment]
Made a new project for the CC cookbook, but I'll have to update it once Gwen gets a github account.

**Comment by janeatcc** [comment]
Added @sarahpearson as driver of start-up - at least to fill out template and initiate conversation about whether we should pursue or not

**Comment by janeatcc** [comment]
I removed the list:
*User-centered design as a project (for now) per thread about it on staff list 
*resources for GLAM - b/c I don't want to do it, at least as a separate project, if other want to feel free to create a project and fill out template
*plan to engage single content provider websites - also b/c i don't want to do it, and b/c I think it can be ad-hoc and/or enveloped in platform work, which we can discuss

**Comment by mattl** [comment]
Taking this, as I think my projects are the outstanding (as in not done, not as in good) ones.

**Comment by janeatcc** [comment]
Adding back plan to engage single content provider websites re our discussion today. It should be a separate project from platform initiative - taking as to do to add for me.

**Comment by janeatcc** [comment]
@cablegreen are we still doing the Open Education affiliate calls? If so, should we add it as a separate project here? Or do you think it doesn't need a GitHub page? Or can it be enveloped with a larger project?

**Comment by cablegreen** [comment]
Hi Jane - I think this falls within our standard open education work ...
and does not need a separate project in GitHub.

Cable

On Mon, Mar 9, 2015 at 4:09 PM, Jane <notifications@github.com> wrote:

> @cablegreen <https://github.com/cablegreen> are we still doing the Open
> Education affiliate calls? If so, should we add it as a separate project
> here? Or do you think it doesn't need a GitHub page? Or can it be enveloped
> with a larger project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/meta/issues/1#issuecomment-77964180>.
>



-- 

Cable

**Comment by janeatcc** [comment]
@mattl please add DACI + HCD to CC search project per our thread the other day

**Comment by janeatcc** [comment]
Can I get permissions to create new repo? or can either @sarahpearson or @mattl create a new project "Single provider website adoptions" for me? Thanks!

**Comment by mattl** [comment]
Can we make new issues for new things please?
