### ISSUE TITLE
Please create a new reposistory for Roadmaps update

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/meta#14]
Thanks! ;)

**Comment by mattl** [comment]
What are Roadmaps updates?

**Comment by claudioruiz** [comment]
It's a new project I'm planning to work on. We have [roadmaps templates](https://wiki.creativecommons.org/Roadmap_Template) very difficult to fill in for affiliates and not very good at provide useful information for us. I'm working into a new proposal after some consultations with affiliates. I can do it without github, anyway.
