### ISSUE TITLE
Set up jx-specific PDM project and patents rights project on github

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/meta#4]
Please set up two new projects on github, as described in this document:  https://docs.google.com/document/d/1P7iyaGC6GZxwe06ROjLiRaX7zp2fq4C6bkqRaYeXFNc/edit?usp=sharing

**Comment by mattl** [comment]
Do you have a preferred name for the projects?

**Comment by peterspdx** [comment]
The names that are in the document I link to are good, at least for now.  Thanks.
