### ISSUE TITLE
send out staff guidelines about how to use github 

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/meta#7]
I'm getting the sense that we should give people some basic guidance about when/how to create issues, how to set those against the 2-week milestones, etc. 

@mattl do you want me to write something up about this, or do you think we should just wait until your hangout about github for staff next week?

**Comment by mattl** [comment]
I have a new secret project for us. I'll tell you tomorrow.

**Comment by peterspdx** [comment]
That's anti-transparency and working in the open, right?  Sarah's query is the very question I asked on our last staff call on the "when" (not the how) -- what's too specific, what's not specific enough.  Confession, I haven't yet created milestones for the projects I'm driving or am accountable on, so I welcome hearing from matt and sarah.  But it would be nice if there was a conversation to hear how people are feeling before secret conversations (if ever) are in order :-)

**Comment by mattl** [comment]
Our project will be on GitHub from day 1.

We just might not share it as documentation on day 1.
