### ISSUE TITLE
cc-devel users to add to GitHub

### ISSUE THREAD

**Issue by mattl** [creativecommons/meta#8]

**Comment by ffledgling** [comment]
Not sure if there's any criteria for addition, I mostly lurk around the cc-devel list, but I'd be happy to contribute to any projects that look interesting.

**Comment by mattl** [comment]
@ffledgling welcome.

**Comment by jenmontes** [comment]
Hey! I've also been lurking recently but I'd like to do more!

**Comment by robmyers** [comment]
Boo.

**Comment by asmith15** [comment]
Please add me too

**Comment by Dylan5150** [comment]
Add pls

**Comment by AbhishekKumarSingh** [comment]
Add me too.

**Comment by tarmot** [comment]
me2

**Comment by jonasob** [comment]
Likewise!

**Comment by mattl** [comment]
Okay, everyone up to Jonas has been invited. Keep them coming :)

**Comment by mzeinstra** [comment]
You have me already right?

**Comment by mozodev** [comment]
Me too, Thanks!

**Comment by mattl** [comment]
@mozodev -- added you @mzeinstra -- you're already in our list :)
